export const hackathons = [
  {
    project: "Milionario",
    hackathon: "ETHOnline 2024",
    location: "Online 🌍",
    date: "September 2024",
    description:
      "Developed 1in1million game as XMTP bot with Farcaster OpenFrames, Chainlink VRF for randomness and Web3auth for authentication on the webapp.",
    tags: ["XMTP", "Chainlink", "Web3auth"],
    github: "https://github.com/builders-garden/xmtp-1in1million",
    website: "https://a-milly.vercel.app/",
    image: "/hackathons/milionario.png",
  },
  {
    project: "SnappyAI",
    hackathon: "ETHGlobal Brussels 2024",
    location: "Brussels 🇧🇪",
    date: "July 2024",
    description:
      "Developed a custom v4 hook for PancakeSwap and helped w the React Frontend. Winner with Metamask Snap and Blockscout.",
    tags: ["Metamask", "Brian", "PancakeSwap"],
    github: "https://github.com/Che-Scoppiati/SnappyAI",
    website: "https://snappyai.vercel.app/",
    image: "/hackathons/snappy_ai.png",
  },
  {
    project: "Shopycast",
    hackathon: "Base Onchain Summer",
    location: "Online 🌍",
    date: "June 2024",
    description:
      "Shopify integration with Farcaster. Build in seconds your Shopify frame and let users fill their cart directly on Farcaster.",
    tags: ["Farcaster", "Shopify", "Base"],
    github: "https://github.com/Che-Scoppiati/shopycast",
    website: "https://shopycast.xyz/",
    image: "/hackathons/shopycast.png",
  },
  {
    project: "JPEG Station",
    hackathon: "ETHDam 2024",
    location: "Amsterdam 🇳🇱",
    date: "April 2024",
    description:
      "Frontend for JPEG Station, Cross-chain swaps between NFTs and Ordinals with Near chain-signatures. Winner with Near.",
    tags: ["Near", "Ordinals", "NFT"],
    github: "https://github.com/0xCaso/jpeg-station",
    website: "https://jpeg-station.vercel.app/",
    image: "/hackathons/jpeg_station.png",
  },
  {
    project: "eulSynths",
    hackathon: "ETHDenver 2024",
    location: "Denver 🇺🇸",
    date: "February 2024",
    description:
      "eulSynths is a universal DeFi yield product platform built on Euler and Balancer. The protocol allows users to leverage DEX liquidity from protocols like Balancer to multiply their intrinsic yield.",
    tags: ["DeFi", "Euler", "Balancer"],
    github: "https://github.com/1delta-DAO/eth-denver-eul-synths",
    website: "https://eth-denver-eul-synths.vercel.app/",
    image: "/hackathons/eulsynths.png",
  },
  {
    project: "FairPetuals",
    hackathon: "CTRL+Hack+ZK",
    location: "Online 🌍",
    date: "January 2024",
    description:
      "FairPetual is the first perpetuals platform that allows for fair liquidations where anyone can earn a share of fee income by spotting positions that can be liquidated early and execute the liquidations themselves.",
    tags: ["DeFi", "Aleph Zero"],
    github: "https://github.com/1delta-DAO/ctrl-plus-fairpetual",
    website: "https://ctrl-plus-fairpetual-frontend.vercel.app/",
    image: "/hackathons/fairpetuals.png",
  },
  {
    project: "BountyArena",
    hackathon: "ETHRome 2023",
    location: "Rome 🇮🇹",
    date: "October 2023",
    description:
      "Fronted Dev for BountyArena Leveraging the Blockchain to help companies create and fund opensource solution to their problems with reputation. Winner with TalentLayer, The Graph, ENS.",
    tags: ["TalentLayer", "The Graph", "ENS"],
    github: "https://github.com/bianc8/BountyArena",
    website: "https://bountyarena.vercel.app/",
    image: "/hackathons/bountyarena.png",
  },
  {
    project: "Sismord",
    hackathon: "ETHDam 2023",
    location: "Amsterdam 🇳🇱",
    date: "May 2023",
    description:
      "Built the Frontend in React for Sismord: Gated access to Discord servers leveraging blockchain and Sismo data vaults. Winner of Best data aggregation with Sismo @ETHDam 2023.",
    tags: ["Sismo"],
    github: "https://github.com/0xCaso/sismord-discord-bot",
    website: "https://devfolio.co/projects/sismord-af06",
    image: "/hackathons/sismord.png",
  },
  {
    project: "FantaCrypto",
    hackathon: "Ethereum Zurich 2023",
    location: "Zurich 🇨🇭",
    date: "April 2023",
    description:
      "Built the Frontend in React for Sismord: Gated access to Discord servers leveraging blockchain and Sismo data vaults. Winner of Best data aggregation with Sismo @ETHDam 2023.",
    tags: ["API3"],
    github: "https://github.com/0xCaso/FantaCrypto/tree/main",
    website: "https://devfolio.co/projects/fantacrypto-f046",
    image: "/hackathons/fantacrypto.png",
  },
  {
    project: "Sismord",
    hackathon: "ZKHack 2023",
    location: "Lisbon 🇵🇹",
    date: "March 2023",
    description:
      "Built the Frontend in React for Sismord: Gated access to Discord servers leveraging blockchain and Sismo data vaults. Winner of Best data aggregation with Sismo @ETHDam 2023.",
    tags: ["Sismo"],
    github: "https://github.com/0xCaso/sismord-discord-bot",
    website: "https://devfolio.co/projects/sismord-af06",
    image: "/hackathons/sismord.png",
  },
];
